language: ruby
rvm:
  - 2.4.2
services:
  - postgresql
before_install:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database gorails_test;' -U postgres
  - sudo apt-get -qq update
  - sudo apt-get install -y build-essential patch ruby-dev zlib1g-dev liblzma-dev libgmp-dev
script:
  - export RAILS_ENV=test
  - bundle exec rake db:create db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec
after_success:
  - coveralls
