class Album < ActiveRecord::Base
  # main config ...............................................................
  # extends ...................................................................
  # includes ..................................................................
  include PublicActivity::Model
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images,allow_destroy: true, reject_if: :all_blank
  # validations ...............................................................
  validates_presence_of :title
  validates_uniqueness_of :title
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
   tracked owner: ->(controller, model) { controller && controller.current_user }
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
