# app/models/registration.rb
# Model for events registrations
class Registration < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  rewarding
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :event
  belongs_to :user, foreign_key: "user_id"
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  def self.is_registrated?(user_id)
    return true if self.where(user_id: user_id).count >= 1
    false
  end

  def self.to_register(user_id)
    self.create(user_id: user_id)
  end
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end

